nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é', nome.upper())
print('Seu nome em minúsculas é', nome.lower())
quantidade = nome.split()
#print('Seu nome tem ao todo ', len(''.join(quantidade)), 'letras')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")} letras')
#print(f'Seu primeiro nome é {quantidade[0]} e ele tem {len(quantidade[0])} letras')
print(f'Seu primeiro nome tem {nome.find(" ")} letras')